export const ABI = {
  address: "0xd2a72a619bba781a73de84ff4d6ca8512322499ddc263ad7587a116a993f1bce",
  name: "Staking",
  friends: [],
  exposed_functions: [
    {
      name: "create_vote",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "0x1::string::String",
        "0x1::string::String",
        "u64",
        "u64",
      ],
      return: [],
    },
    {
      name: "declare_winner",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64"],
      return: [],
    },
    {
      name: "get_staked_balance",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["u64"],
    },
    {
      name: "get_vault_addr",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["address"],
    },
    {
      name: "stake",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64"],
      return: [],
    },
    {
      name: "unstake",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64"],
      return: [],
    },
    {
      name: "vote",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64", "u64", "bool"],
      return: [],
    },
  ],
  structs: [
    {
      name: "StakedBalance",
      is_native: false,
      abilities: ["store", "key"],
      generic_type_params: [],
      fields: [{ name: "staked_balance", type: "u64" }],
    },
    {
      name: "Vault",
      is_native: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [{ name: "extend_ref", type: "0x1::object::ExtendRef" }],
    },
    {
      name: "Vote",
      is_native: false,
      abilities: ["store"],
      generic_type_params: [],
      fields: [
        { name: "id", type: "u64" },
        { name: "title", type: "0x1::string::String" },
        { name: "description", type: "0x1::string::String" },
        { name: "start_time", type: "u64" },
        { name: "end_time", type: "u64" },
        { name: "total_yes_votes", type: "u64" },
        { name: "total_no_votes", type: "u64" },
        { name: "completed", type: "bool" },
        { name: "voters", type: "vector<address>" },
      ],
    },
    {
      name: "VoteRepository",
      is_native: false,
      abilities: ["store", "key"],
      generic_type_params: [],
      fields: [
        {
          name: "votes",
          type: "vector<0xd2a72a619bba781a73de84ff4d6ca8512322499ddc263ad7587a116a993f1bce::Staking::Vote>",
        },
      ],
    },
  ],
} as const;
